-- V10: Seed do Plano de Contas baseado na Classificação de Despesas

INSERT INTO expense_categories (code, name, group_code, group_name, is_income) VALUES
-- Grupo 1: Recursos Humanos
('1.1',  'Vencimentos e Salarios',                    '1', 'Recursos Humanos',  FALSE),
('1.2',  'Ferias',                                    '1', 'Recursos Humanos',  FALSE),
('1.3',  '13 Salario',                                '1', 'Recursos Humanos',  FALSE),
('1.4',  'Ferias - Abono Pecuniario',                 '1', 'Recursos Humanos',  FALSE),
('1.5',  'Ferias - Abono Constitucional',             '1', 'Recursos Humanos',  FALSE),
('1.6',  'Outras Despesas Fixas - Pessoal Civil',     '1', 'Recursos Humanos',  FALSE),
('1.7',  'Aviso Previo',                              '1', 'Recursos Humanos',  FALSE),
('1.8',  'Outras Despesas Variaveis - Pessoal Civil', '1', 'Recursos Humanos',  FALSE),
('1.9',  'TRCT',                                      '1', 'Recursos Humanos',  FALSE),
-- Grupo 2: Encargos Trabalhistas
('2.1',  'INSS - Cota Patronal',                      '2', 'Encargos Trabalhistas',  FALSE),
('2.2',  'FGTS',                                      '2', 'Encargos Trabalhistas',  FALSE),
('2.3',  'FGTS - Multa Rescisoria',                   '2', 'Encargos Trabalhistas',  FALSE),
('2.4',  'IRRF',                                      '2', 'Encargos Trabalhistas',  FALSE),
('2.5',  'PIS/PASEP sobre Folha',                     '2', 'Encargos Trabalhistas',  FALSE),
('2.6',  'Outras Obrigacoes Patronais',               '2', 'Encargos Trabalhistas',  FALSE),
-- Grupo 3: Beneficios
('3.1',  'Auxilio Alimentacao',                       '3', 'Beneficios',  FALSE),
('3.2',  'Fornecimento de Alimentacao Funcionarios',  '3', 'Beneficios',  FALSE),
('3.3',  'Vale-Transporte - Cota Patronal',           '3', 'Beneficios',  FALSE),
('3.4',  'Convenio Odontologico/Medico/Farmacia',     '3', 'Beneficios',  FALSE),
('3.5',  'Convenios Medico/Odontologicos Patronal',   '3', 'Beneficios',  FALSE),
-- Grupo 4: Despesas com Pessoal
('4.1',  'Servicos de Pericias Medicas',              '4', 'Despesas com Pessoal',  FALSE),
('4.2',  'Seguro de Vida',                            '4', 'Despesas com Pessoal',  FALSE),
-- Grupo 5: Materiais de Consumo
('5.1',  'Combustiveis e Lubrificantes',              '5', 'Materiais de Consumo',  FALSE),
('5.2',  'Gas Engarrafado',                           '5', 'Materiais de Consumo',  FALSE),
('5.3',  'Generos de Alimentacao',                    '5', 'Materiais de Consumo',  FALSE),
('5.4',  'Material Farmacologico',                    '5', 'Materiais de Consumo',  FALSE),
('5.5',  'Material Educativo e Esportivo',            '5', 'Materiais de Consumo',  FALSE),
('5.6',  'Material para Festividades e Homenagens',   '5', 'Materiais de Consumo',  FALSE),
('5.7',  'Material de Expediente',                    '5', 'Materiais de Consumo',  FALSE),
('5.8',  'Material de Processamento de Dados',        '5', 'Materiais de Consumo',  FALSE),
('5.9',  'Material de Cama, Mesa e Banho',            '5', 'Materiais de Consumo',  FALSE),
('5.10', 'Material de Copa e Cozinha',                '5', 'Materiais de Consumo',  FALSE),
('5.11', 'Material de Limpeza e Higienizacao',        '5', 'Materiais de Consumo',  FALSE),
('5.12', 'Uniformes, Tecidos e Aviamentos',           '5', 'Materiais de Consumo',  FALSE),
('5.13', 'Material para Manutencao de Bens Imoveis',  '5', 'Materiais de Consumo',  FALSE),
('5.14', 'Material para Manutencao de Bens Moveis',   '5', 'Materiais de Consumo',  FALSE),
('5.15', 'Material de Protecao e Seguranca',          '5', 'Materiais de Consumo',  FALSE),
('5.16', 'Material Hospitalar',                       '5', 'Materiais de Consumo',  FALSE),
('5.17', 'Ferramentas',                               '5', 'Materiais de Consumo',  FALSE),
('5.18', 'Material Didatico',                         '5', 'Materiais de Consumo',  FALSE),
('5.19', 'Outros Materiais de Consumo',               '5', 'Materiais de Consumo',  FALSE),
('5.20', 'Alimentos para Animais',                    '5', 'Materiais de Consumo',  FALSE),
('5.21', 'Material de Coudelaria',                    '5', 'Materiais de Consumo',  FALSE),
('5.22', 'Materiais e Medicamentos Veterinarios',     '5', 'Materiais de Consumo',  FALSE),
-- Grupo 6: Locacao de Mao de Obra
('6.1',  'Apoio Administrativo, Tecnico e Operacional', '6', 'Locacao de Mao de Obra',  FALSE),
('6.2',  'Limpeza e Conservacao - Mao de Obra',       '6', 'Locacao de Mao de Obra',  FALSE),
('6.3',  'Vigilancia Ostensiva',                      '6', 'Locacao de Mao de Obra',  FALSE),
('6.4',  'Manutencao de Bens Imoveis - Mao de Obra',  '6', 'Locacao de Mao de Obra',  FALSE),
('6.5',  'Servicos de Copa e Cozinha - Mao de Obra',  '6', 'Locacao de Mao de Obra',  FALSE),
('6.6',  'Manutencao de Bens Moveis - Mao de Obra',   '6', 'Locacao de Mao de Obra',  FALSE),
('6.7',  'Outras Locacoes de Mao de Obra',            '6', 'Locacao de Mao de Obra',  FALSE),
-- Grupo 7: Servicos de Terceiros
('7.1',  'Aquisicao de Softwares',                    '7', 'Servicos de Terceiros',  FALSE),
('7.2',  'Bolsa de Iniciacao ao Trabalho',            '7', 'Servicos de Terceiros',  FALSE),
('7.3',  'Condominios',                               '7', 'Servicos de Terceiros',  FALSE),
('7.4',  'Confeccao de Uniformes e Bandeiras',        '7', 'Servicos de Terceiros',  FALSE),
('7.5',  'Estagiarios',                               '7', 'Servicos de Terceiros',  FALSE),
('7.6',  'Festividades e Homenagens',                 '7', 'Servicos de Terceiros',  FALSE),
('7.7',  'Fornecimento de Alimentacao',               '7', 'Servicos de Terceiros',  FALSE),
('7.8',  'Fretes e Transportes',                      '7', 'Servicos de Terceiros',  FALSE),
('7.9',  'Hospedagens',                               '7', 'Servicos de Terceiros',  FALSE),
('7.10', 'Limpeza e Conservacao - Terceiros',         '7', 'Servicos de Terceiros',  FALSE),
('7.11', 'Locacao de Imoveis',                        '7', 'Servicos de Terceiros',  FALSE),
('7.12', 'Locacao de Maquinas e Equipamentos',        '7', 'Servicos de Terceiros',  FALSE),
('7.13', 'Manutencao de Bens Imoveis - Terceiros',    '7', 'Servicos de Terceiros',  FALSE),
('7.14', 'Manutencao de Maquinas e Equipamentos',     '7', 'Servicos de Terceiros',  FALSE),
('7.25', 'Servicos Medico-Hospitalar e Laboratorial', '7', 'Servicos de Terceiros',  FALSE),
('7.28', 'Servicos Tecnicos Profissionais',           '7', 'Servicos de Terceiros',  FALSE),
('7.34', 'Locacao de Software',                       '7', 'Servicos de Terceiros',  FALSE),
('7.37', 'Outros Servicos de Terceiros - PJ',         '7', 'Servicos de Terceiros',  FALSE),
-- Grupo 8: Servicos Publicos
('8.1',  'Servicos de Agua e Esgoto',                 '8', 'Servicos Publicos',  FALSE),
('8.2',  'Servicos de Energia Eletrica',              '8', 'Servicos Publicos',  FALSE),
('8.4',  'Telefonia e Internet',                      '8', 'Servicos Publicos',  FALSE),
-- Grupo 9: Despesas Diversas
('9.5',  'Aparelhos e Utensilios Domesticos',         '9', 'Despesas Diversas',  FALSE),
-- Grupo 10: Creditos (Receitas)
('10.1', 'Repasse',                                   '10', 'Creditos',  TRUE),
('10.2', 'Rendimento Liquido de Aplicacoes',          '10', 'Creditos',  TRUE),
('10.3', 'Contrapartida',                             '10', 'Creditos',  TRUE),
('10.4', 'Outras Receitas',                           '10', 'Creditos',  TRUE),
-- Categorias operacionais extras (usadas nos lancamentos reais)
('11.1', 'Contribuicoes de Associados',               '11', 'Receitas Operacionais',  TRUE),
('11.2', 'Assessoria e Consultoria Recebida',         '11', 'Receitas Operacionais',  TRUE),
('11.3', 'Transferencias entre Contas',               '11', 'Receitas Operacionais',  TRUE),
('12.1', 'Juros e Multas',                            '12', 'Despesas Financeiras',  FALSE),
('12.2', 'Despesas Bancarias - Tarifas',              '12', 'Despesas Financeiras',  FALSE),
('12.3', 'Consorcio',                                 '12', 'Despesas Financeiras',  FALSE),
('13.1', 'Doacoes',                                   '13', 'Despesas Sociais',  FALSE),
('13.2', 'Estornos para Pacientes',                   '13', 'Despesas Sociais',  FALSE),
('13.3', 'Reembolsos em Geral',                       '13', 'Despesas Sociais',  FALSE),
('13.4', 'Consultas Medicas',                         '13', 'Despesas Sociais',  FALSE),
('14.1', 'Material - Cultivo',                        '14', 'Atividade Fim',  FALSE),
('14.2', 'Faculdade',                                 '14', 'Atividade Fim',  FALSE),
('14.3', 'Relogio de Ponto',                          '14', 'Atividade Fim',  FALSE);
